// Данные каталога ResiNDart.
// Чтобы временно скрыть товар, установите published: false.
// Для фотографии укажите путь image и альтернативное описание imageAlt.
window.RESINDART_PRODUCTS = [
  { id: 1, published: true, category: "clock", categoryName: "Часы", name: "Тихая глубина", status: "available", statusName: "В наличии", price: "8 900 ₽", size: "Ø 40 см", time: "Готово к отправке", image: "assets/product-clock-emerald.png", imageAlt: "Часы из изумрудной эпоксидной смолы и тёмного дерева", description: "Настенные часы в глубоком зелёном оттенке с тёплыми металлическими акцентами." },
  { id: 2, published: true, category: "clock", categoryName: "Часы", name: "Полярный берег", status: "order", statusName: "Под заказ", price: "от 9 500 ₽", size: "Ø 45 см", time: "14–21 день", description: "Светлая композиция с плавным рисунком, напоминающим линию морского берега." },
  { id: 3, published: true, category: "clock", categoryName: "Часы", name: "Янтарный круг", status: "order", statusName: "Под заказ", price: "от 8 500 ₽", size: "Ø 35 см", time: "14–21 день", description: "Камерные часы с янтарными переходами и выразительной природной фактурой." },
  { id: 4, published: true, category: "decor", categoryName: "Посуда и декор", name: "Лесное озеро", status: "available", statusName: "В наличии", price: "4 600 ₽", size: "38 × 24 см", time: "Готово к отправке", description: "Сервировочный поднос с мягким зелёным рисунком и удобными ручками." },
  { id: 5, published: true, category: "decor", categoryName: "Посуда и декор", name: "Северный свет", status: "order", statusName: "Под заказ", price: "от 3 200 ₽", size: "Комплект из 4 шт.", time: "10–14 дней", description: "Комплект подставок с прозрачными слоями и холодными серебристыми деталями." },
  { id: 6, published: true, category: "decor", categoryName: "Посуда и декор", name: "Золотой лист", status: "available", statusName: "В наличии", price: "5 800 ₽", size: "Ø 30 см", time: "Готово к отправке", description: "Декоративное блюдо с тонким золотистым акцентом для сервировки или интерьера." },
  { id: 7, published: true, category: "table", categoryName: "Столы", name: "Малахит", status: "order", statusName: "Под заказ", price: "от 42 000 ₽", size: "Ø 60 × 50 см", time: "30–45 дней", description: "Акцентный столик с выразительным рисунком столешницы и лаконичным основанием." },
  { id: 8, published: true, category: "table", categoryName: "Столы", name: "Ночная вода", status: "order", statusName: "Под заказ", price: "от 58 000 ₽", size: "90 × 55 × 45 см", time: "30–45 дней", description: "Журнальный стол с глубоким синим цветом и спокойным глянцевым отражением." },
  { id: 9, published: true, category: "table", categoryName: "Столы", name: "Тёплый берег", status: "order", statusName: "Под заказ", price: "от 48 000 ₽", size: "70 × 45 × 52 см", time: "30–45 дней", description: "Приставной столик с сочетанием древесной фактуры и прозрачной заливки." },
  { id: 10, published: true, category: "art", categoryName: "Картины", name: "Течение", status: "available", statusName: "В наличии", price: "12 000 ₽", size: "60 × 80 см", time: "Готово к отправке", description: "Абстрактная интерьерная работа с несколькими слоями цвета и ощущением движения." },
  { id: 11, published: true, category: "art", categoryName: "Картины", name: "Воздух", status: "order", statusName: "Под заказ", price: "от 14 000 ₽", size: "70 × 90 см", time: "21–30 дней", description: "Светлая композиция для спокойного интерьера, создаваемая в выбранной палитре." },
  { id: 12, published: true, category: "art", categoryName: "Картины", name: "Глубина леса", status: "available", statusName: "В наличии", price: "16 500 ₽", size: "80 × 100 см", time: "Готово к отправке", description: "Многослойная работа в зелёных и графитовых оттенках с золотистыми деталями." },
];
